version: '3'

services:
  mongodb:
    image: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - 27017:27017
  starter:
    build: ./expressapp
    ports:
      - 3000:3000
    depends_on:
      - mongodb